### ISSUE TITLE
[cryptid compat] Glitched cards broken

### ISSUE THREAD

**Issue by DigitalDetective47** [stupxd/Cartomancer#1]
In the deck view, glitched cards (cryptid) show incorrect values. Their values change when tabs are changed, and do not reflect their actual values. Also, glitched cards (imo) should only stack if they have the same values.

**Comment by stupxd** [comment]
It is intentional that cards with different chip values go into the same stack, I can add an option for that though.

**Comment by stupxd** [comment]
Added in latest release
