### ISSUE TITLE
card stacking in deck view broken

### ISSUE THREAD

**Issue by DigitalDetective47** [stupxd/Cartomancer#2]
![20241220030508_1](https://github.com/user-attachments/assets/ff172277-3d61-46d5-a69e-023ee02162b4)

**Comment by stupxd** [comment]
What mods do you have installed? some mods override deck view which would cause this

**Comment by stupxd** [comment]
Nevermind. Seems like Steamodded changed a few things that's why it's failing. Will fix soon
